---
# handlers file for ansible-observium-unixagent

- name: xinetd restart
  become: true
  service:
    name: xinetd
    state: restarted

- name: restart lighttpd
  service:
    name: lighttpd
    state: restarted
